# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppPartialDerivative <- function(Q, N, K, epsDeriv, ll_d2, F, init, dumMat, nbCluster) {
    .Call(`_FENmlm_RcppPartialDerivative`, Q, N, K, epsDeriv, ll_d2, F, init, dumMat, nbCluster)
}

RcppPartialDerivative_gaussian <- function(Q, N, K, epsDeriv, F, init, dumMat, nbCluster) {
    .Call(`_FENmlm_RcppPartialDerivative_gaussian`, Q, N, K, epsDeriv, F, init, dumMat, nbCluster)
}

RcppPartialDerivative_other <- function(Q, N, epsDeriv, ll_d2, dx_dother, init, dumMat, nbCluster) {
    .Call(`_FENmlm_RcppPartialDerivative_other`, Q, N, epsDeriv, ll_d2, dx_dother, init, dumMat, nbCluster)
}

RcppGetFE <- function(Q, N, S, dumMat, nbCluster, obsCluster) {
    .Call(`_FENmlm_RcppGetFE`, Q, N, S, dumMat, nbCluster, obsCluster)
}

cpp_NB_dum_fx <- function(theta, lhs, mu, x1, obsCluster, start, end) {
    .Call(`_FENmlm_cpp_NB_dum_fx`, theta, lhs, mu, x1, obsCluster, start, end)
}

cpp_NB_dum_dfx <- function(theta, lhs, mu, x1, obsCluster, start, end) {
    .Call(`_FENmlm_cpp_NB_dum_dfx`, theta, lhs, mu, x1, obsCluster, start, end)
}

RcppCreate_start_end_indexes <- function(nbCluster, tableCluster_vect) {
    .Call(`_FENmlm_RcppCreate_start_end_indexes`, nbCluster, tableCluster_vect)
}

RcppDichotomyNR <- function(N, K, family, theta, epsDicho, lhs, mu, borne_inf, borne_sup, obsCluster, tableCluster) {
    .Call(`_FENmlm_RcppDichotomyNR`, N, K, family, theta, epsDicho, lhs, mu, borne_inf, borne_sup, obsCluster, tableCluster)
}

cpp_conditional_minMaxMean <- function(K, N, mu, dum, tableCluster) {
    .Call(`_FENmlm_cpp_conditional_minMaxMean`, K, N, mu, dum, tableCluster)
}

cpp_conditional_minMax <- function(K, N, mu, dum, tableCluster) {
    .Call(`_FENmlm_cpp_conditional_minMax`, K, N, mu, dum, tableCluster)
}

cpp_tapply_sum <- function(Q, x, dum) {
    .Call(`_FENmlm_cpp_tapply_sum`, Q, x, dum)
}

cpp_tapply_vsum <- function(Q, x, dum) {
    .Call(`_FENmlm_cpp_tapply_vsum`, Q, x, dum)
}

cpp_table <- function(Q, dum) {
    .Call(`_FENmlm_cpp_table`, Q, dum)
}

cpp_unik_id <- function(x_sorted) {
    .Call(`_FENmlm_cpp_unik_id`, x_sorted)
}

Rcpp_compute_sum_clusters <- function(N, Q, family, theta, epsMu, init, lhs, sum_y, mu, dum_vect, nbCluster, tableCluster_vect, obsCluster_vect, start_cluster_vect, end_cluster_vect) {
    .Call(`_FENmlm_Rcpp_compute_sum_clusters`, N, Q, family, theta, epsMu, init, lhs, sum_y, mu, dum_vect, nbCluster, tableCluster_vect, obsCluster_vect, start_cluster_vect, end_cluster_vect)
}

Rcpp_unclassFactor <- function(x) {
    .Call(`_FENmlm_Rcpp_unclassFactor`, x)
}

Rcpp_Ax_Ais1 <- function(dumMat, nbCluster, tableCluster_all, x) {
    .Call(`_FENmlm_Rcpp_Ax_Ais1`, dumMat, nbCluster, tableCluster_all, x)
}

new_cpp_NB_dum_fx <- function(theta, lhs, exp_mu, x1, obsCluster, start, end) {
    .Call(`_FENmlm_new_cpp_NB_dum_fx`, theta, lhs, exp_mu, x1, obsCluster, start, end)
}

new_cpp_NB_dum_dfx <- function(theta, lhs, exp_mu, x1, obsCluster, start, end) {
    .Call(`_FENmlm_new_cpp_NB_dum_dfx`, theta, lhs, exp_mu, x1, obsCluster, start, end)
}

new_RcppDichotomyNR <- function(N, K, family, theta, epsDicho, lhs, exp_mu, borne_inf, borne_sup, obsCluster, tableCluster) {
    .Call(`_FENmlm_new_RcppDichotomyNR`, N, K, family, theta, epsDicho, lhs, exp_mu, borne_inf, borne_sup, obsCluster, tableCluster)
}

